version: "3.3"
services: 
  mongodb:
    image: mongo:latest
    container_name: "blockchain"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    networks:
      - blocknetwork
networks:
  blocknetwork: 